version: "3.9"

services:
    nginx:
        build: nginx/
        container_name: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
             - frontend
        volumes:
            - wp-files:/wordpress/
        restart: always

    wordpress:
        build: wordpress/
        container_name: wordpress
        depends_on:
            - mariadb
        env_file:
            - .env
        networks:
            - frontend
            - backend
        volumes:
            - wp-files:/wordpress/
        restart: always

    mariadb:
        build: mariadb/
        container_name: mariadb
        env_file:
            - .env
        networks:
            - backend
        volumes:
            - db-files:/var/lib/mysql/
        restart: always

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    wp-files:
    db-files:
